# Generated by Django 3.0.6 on 2020-05-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('FD', 'Продукты'), ('SV', 'Услуги'), ('AP', 'Техника'), ('PT', 'АЗС'), ('RT', 'Рестораны')], default='FD', max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('added', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_api.BotUser')),
            ],
        ),
        migrations.CreateModel(
            name='BotUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.ManyToManyField(to='tracker_api.Expense')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker_api.BotUser')),
            ],
        ),
    ]
