# Generated by Django 3.0.6 on 2020-05-23 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
